services:
  backend:
    build: ./services/backend
    container_name: fastapi-container
    command: uvicorn src.main:app --host 0.0.0.0 --port 8088 --reload
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@postgres:5432/hello_fastapi_dev
    ports:
      - 8088:8088
    volumes:
      - ./services/backend:/code
    depends_on:
      - postgres

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  postgres:
    image: postgres:15.2
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - postgres

volumes:
  postgres_data:
  pgadmin:


  # redis_db:
  #   container_name: redis_db
  #   #command: bash -c "redis-server --appendonly yes --requirepass <password>"
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis-volume:/data
